// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvcl4.Context;

#nullable disable

namespace mvcl4.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250919132435_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mvcl4.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "SWE"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "CS"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "IS"
                        },
                        new
                        {
                            DeptId = 4,
                            DeptName = "IT"
                        },
                        new
                        {
                            DeptId = 5,
                            DeptName = "AI"
                        },
                        new
                        {
                            DeptId = 6,
                            DeptName = "BIO"
                        });
                });

            modelBuilder.Entity("mvcl4.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Menoufia",
                            Age = 25,
                            DeptId = 1,
                            Email = "ahmed.ali@example.com",
                            Name = "Ahmed Ali",
                            Password = "pass1234"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza",
                            Age = 30,
                            DeptId = 2,
                            Email = "mona.said@example.com",
                            Name = "Mona Said",
                            Password = "mona456"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria",
                            Age = 2,
                            DeptId = 3,
                            Email = "youssef.g@example.com",
                            Name = "Youssef Gamal",
                            Password = "you12345"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mansoura",
                            Age = 22,
                            DeptId = 1,
                            Email = "sara.fathy@example.com",
                            Name = "Sara Fathy",
                            Password = "sara987"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Tanta",
                            Age = 35,
                            DeptId = 2,
                            Email = "khaled.n@example.com",
                            Name = "Khaled Nour",
                            Password = "khaledpw"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Zagazig",
                            Age = 27,
                            DeptId = 3,
                            Email = "nour.hassan@example.com",
                            Name = "Nour Hassan",
                            Password = "nourpass"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ismailia",
                            Age = 29,
                            DeptId = 1,
                            Email = "omar.adel@example.com",
                            Name = "Omar Adel",
                            Password = "omar123"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Aswan",
                            Age = 32,
                            DeptId = 2,
                            Email = "laila.samir@example.com",
                            Name = "Laila Samir",
                            Password = "laila321"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Menoufia",
                            Age = 26,
                            DeptId = 3,
                            Email = "hassan.omar@example.com",
                            Name = "Hassan Omar",
                            Password = "hassanpw"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Luxor",
                            Age = 24,
                            DeptId = 4,
                            Email = "dina.nabil@example.com",
                            Name = "Dina Nabil",
                            Password = "dina444"
                        });
                });

            modelBuilder.Entity("mvcl4.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "mohamed301@gmail.com",
                            FirstName = "mohamed",
                            LastName = "abdelhameed",
                            Password = "mn301"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "nour117@gmail.com",
                            FirstName = "nour",
                            LastName = "abdallah",
                            Password = "mn301"
                        });
                });

            modelBuilder.Entity("mvcl4.Models.Student", b =>
                {
                    b.HasOne("mvcl4.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("mvcl4.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
